<a href="https://colab.research.google.com/github/shwetasharma05072003-crypto/quiz-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import numpy library

In [ ]:
import numpy as np

Creating 1D array

In [ ]:

s=np.array([1,2,3,4,5,6])

Creating 2D array

In [ ]:

s=np.array([[1,2,3,4],[5,6,7,8]])

Print shape

In [ ]:
s.shape

(2, 4)

Print dimension

In [ ]:
s.ndim

2

Print Data type

In [ ]:
s.dtype

dtype('int64')

Size

In [ ]:
s.size

8

arange

In [ ]:
np.arange (10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Linspace

In [ ]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

Extract first element

In [ ]:


b=s[0,0]
print (b)

1


Last element

In [ ]:

c=s[0,3]
print (c)

4


Extract all rows of second column

In [ ]:

d=s[1,:]
print(d)

[5 6 7 8]
